baseurl: https://cinemateatrosestito.com/
languageCode: en-us
title: Cinema Teatro Sestito
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  articoli: /:year/:month/:day/:slug/
  archivio: /:year/:month/:day/:slug/
  eventi: /:year/:month/:day/:slug/
  programmazione-storica: /:year/:month/:day/:slug/
menu:
  main:
    - name: Progetto
      url: /progetto/
      weight: 1
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Un sito web dedicato al Cinema Teatro Sestito, scopri la storia affascinante dell'iconico cinema di San Vito sullo Ionio, Italia. Dalle sue origini alla chiusura, esplora i film, le storie e i ricordi che hanno reso il Cinema una cara istituzione culturale del paese. Il nostro sito web offre una ricca collezione di foto e aneddoti, oltre a informazioni sulla nostra associazione culturale e sugli eventi in programma. Unisciti a noi per celebrare la magia del cinema e il lascito di Vito Sestito, il visionario fondatore di questa gemma cinematografica.
  defaultImage: "https://cinemateatrosestito.com/_index_files/1956_progetto_cinema.webp"
  favicon: images/favicon.png
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: avatar
    height: 50
    url: avatar.png
    width: 50
  instagram: whatswrongintown
  github: whatswrongintown/cinema-teatro-sestito.git
  email: whatswrongintown@gmail.com
  copyright: © 2025 Vito Sestito
  copyrightUrl: https://cinemateatrosestito.com/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: true
  youtube:
    disable: false
    privacyEnhanced: true
assetDir: static
build:
  timeout: 600000
