baseurl: /
languageCode: en-us
title: Cinema Teatro Sestito
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
  documents: /:year/:month/:day/:slug/
  association: /:year/:month/:day/:slug/
  events: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Chi siamo
      url: /about/
      weight: 2
    - name: Associazione
      url: /association/
      weight: 3


params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Un sito web dedicato al Cinema Teatro Sestito, scopri la storia affascinante dell'iconico cinema di San Vito sullo Ionio, Italia. Dalle sue origini alla chiusura, esplora i film, le storie e i ricordi che hanno reso il Cinema una cara istituzione culturale del paese. Il nostro sito web offre una ricca collezione di foto e aneddoti, oltre a informazioni sulla nostra associazione culturale e sugli eventi in programma. Unisciti a noi per celebrare la magia del cinema e il lascito di Vito Sestito, il visionario fondatore di questa gemma cinematografica.
  favicon: logo2.png
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
