---
title: Rubrica Fratelli de Leon 1971
author: Vito Sestito
date: '1971-01-01'
slug: rubrica-fratelli-de-leon-1971
categories:
  - Rubriche
tags:
  - Database
  - Proiezioni
description: "Rubriche dove i film venivano annotati in ordine alfabetico, con data di proiezione e distributore."
---

{{< image-gallery gallery_dir="/images/1971_01_01_rubrica_fratelli_de_leon" >}}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

agende <- read_csv("C:/Users/eurhope/Documents/R/cinema-teatro-sestito/static/data/programmazione_agende.csv") %>%
          select(const, date, title, source)

imdb <- read_csv("C:/Users/eurhope/Documents/R/cinema-teatro-sestito/static/data/programmazione_imdb.csv") %>%
          select(const = Const, year = Year, directors = Directors, genres = Genres, imdb_rating = `IMDb Rating`, runtime = `Runtime (mins)`, url = URL)

rubrica_1971 <- agende %>%
          filter(str_detect(source, "Rubrica 1971")) %>%
          left_join(imdb, by = "const")
```
### Programmazione
```{r echo=FALSE}
rubrica_1971 %>%
          arrange(date) %>%
          mutate(title = str_trunc(title, 60, side = c("right"), ellipsis = "")) %>%
          mutate(title = paste0("[",title,"]","(",url,")")) %>%
          select(date, title) %>%
          knitr::kable(col.names = c("Data", "Titolo"), align = c("l", "l"))
```