---
title: New Europe 1995-00
author: Vito Sestito
date: '1995-10-01'
slug: appunti-new-europe-1995-00
categories:
  - Appunti
description: Appunti su blocchi o fogli, con i film registrati per mese. Riportano gli incassi dei film quando disponibili.
---


{{< image-gallery gallery_dir="/images/1995_10_01_appunti_new_europe_1995_00" >}}


```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(knitr)

# Dati IMDb
imdb <- read_csv(here("static/data/programmazione_imdb.csv")) %>% 
  select(const = Const, url = URL)

# Dati fonte
proiezioni_fonte <- read_csv(here("static/data/programmazione_agende.csv")) %>%
  select(const, date, title, source) %>%
  filter(str_detect(source, "New Europe 1995-00")) %>%
  left_join(imdb, by = "const") %>%
  mutate(title = paste0("[", title, "](", url, ")"))
```


## 1995
### Ottobre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1995, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1995, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1995, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 1996
### Gennaio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1996, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 1997
### Gennaio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1997, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Settembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1997, lubridate::month(date) == 9) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1997, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1997, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1997, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 1998
### Gennaio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Maggio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 5) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Settembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 9) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1998, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 1999
### Gennaio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Maggio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 5) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 1999, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 2000
### Gennaio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Maggio

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 5) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Giugno

```{r echo=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 6) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```


