---
title: Programmazione 1948
author: Vito Sestito
date: '1948-01-01'
slug: programmazione-1948
categories:
  - programmazione-per-anni
---
```{r setup, include=FALSE}
library(dplyr)
library(knitr)
library(readr)
library(lubridate)
library(here)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(scales)

Sys.setlocale("LC_TIME", "it_IT.UTF-8")

# Dati filtrati per l'anno 1948
imdb <- read_csv(here("static/data/programmazione_imdb.csv")) %>%
  select(const = Const, year = Year, directors = Directors,
  genres = Genres, imdb_rating = `IMDb Rating`, imdb_votes = `Num Votes`, runtime = `Runtime (mins)`,
  url = URL)

proiezioni_anno <- read_csv(here("static/data/programmazione_agende.csv")) %>% 
  mutate(anno = year(ymd(date))) %>% 
  left_join(imdb, by = "const") %>% 
  mutate(Titolo = paste0("[", title, "](", url, ")")) %>% 
  filter(anno == 1948) %>% 
  rename(Data = date) %>% 
  arrange(Data)
```
```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=3}
proiezioni_anno %>%
          mutate(mese = month(Data, label = TRUE, abbr = FALSE)) %>%
          count(mese) %>%
          ggplot(aes(x = mese, y = n)) +
          geom_col(fill = "steelblue") +
          geom_text(aes(label = n), vjust = -0.5, size = 4) +
          labs(y = "Numero di film proiettati") +
          theme_classic() +
          theme(strip.placement = "outside",
                strip.background = element_blank(),
                panel.spacing=unit(0,"cm"),
                plot.margin = margin(t = 20, r = 10, b = 10, l = 10)) +
  coord_cartesian(clip = "off")

proiezioni_anno %>%
  drop_na(imdb_rating, imdb_votes) %>%
  ggplot(aes(imdb_votes, imdb_rating)) +
  geom_point(colour = "steelblue", size = 2) +
  geom_text_repel(aes(label = title)) +
  scale_x_log10(labels = comma) +
  scale_y_continuous(breaks = 1:10) +
  labs(y = "Valutazioni medie IMDb", x = "Numero di voti (log)") +
  theme_classic() +
          theme(strip.placement = "outside",
                strip.background = element_blank(),
                panel.spacing=unit(0,"cm"),
                plot.margin = margin(t = 20, r = 10, b = 10, l = 10)) +
  coord_cartesian(clip = "off")
```

### Febbraio
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 2) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Maggio
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 5) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Giugno
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 6) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Luglio
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 7) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Agosto
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 8) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Settembre
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 9) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Ottobre
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 10) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Novembre
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 11) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
### Dicembre
```{r echo=FALSE}
proiezioni_anno %>%
  filter(month(ymd(Data)) == 12) %>%
  select(Data, Titolo) %>%
  arrange(Data) %>%
  kable(col.names = c("", ""))
```
