---
title: Victory 2000
author: Vito Sestito
date: '2000-09-01'
slug: appunti-victory-2000
categories:
  - Appunti
description: Appunti su blocchi o fogli, con i film registrati per mese. Riportano gli incassi dei film quando disponibili.
---


{{< image-gallery gallery_dir="/images/2000_09_01_appunti_victory_2000" >}}


```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(knitr)

# Dati IMDb
imdb <- read_csv(here("static/data/programmazione_imdb.csv")) %>% 
  select(const = Const, url = URL)

# Dati fonte
proiezioni_fonte <- read_csv(here("static/data/programmazione_agende.csv")) %>%
  select(const, date, title, source) %>%
  filter(str_detect(source, "Victory 2000")) %>%
  left_join(imdb, by = "const") %>%
  mutate(title = paste0("[", title, "](", url, ")"))
```


## 2000
### Settembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 9) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2000, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 2001
### Gennaio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Giugno

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 6) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Settembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 9) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2001, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 2002
### Gennaio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2002, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2002, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2002, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2002, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2002, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 2003
### Gennaio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Ottobre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 10) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Novembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 11) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Dicembre

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2003, lubridate::month(date) == 12) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

## 2004
### Gennaio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2004, lubridate::month(date) == 1) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Febbraio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2004, lubridate::month(date) == 2) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Marzo

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2004, lubridate::month(date) == 3) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Aprile

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2004, lubridate::month(date) == 4) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```

### Maggio

```{r echo=FALSE, warning=FALSE}
library(knitr)
proiezioni_fonte %>% 
  filter(lubridate::year(date) == 2004, lubridate::month(date) == 5) %>% 
  select(date, title) %>% 
  arrange(date) %>% 
  kable(col.names = c("", ""))
```


